import Header from "@/components/Header/Header";
import "@/styles/globals.css";
import Head from "next/head";
import { useEffect } from "react";

export default function App({ Component, pageProps }) {
  useEffect(() => {
    // クライアントサイドでのみ実行
    if (typeof window === 'undefined') return;

    // anim_box fadeupクラスを持つ要素を取得
    const trigger = document.querySelectorAll('.anim_box.fadeup');

    if (trigger.length === 0) return;

    // スクロールイベントハンドラー
    const handleScroll = () => {
      for (let i = 0; i < trigger.length; i++) {
        const position = trigger[i].getBoundingClientRect().top;
        const scroll = window.pageYOffset || document.documentElement.scrollTop;
        const offset = position + scroll;
        const windowHeight = window.innerHeight;

        if (scroll > offset - windowHeight + 200) {
          trigger[i].classList.add('is_animated');
        }
      }
    };

    // 初回チェック（既に画面内にある要素を検出）
    handleScroll();

    // スクロールイベントリスナーを追加
    window.addEventListener('scroll', handleScroll);

    // クリーンアップ関数
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [Component]);

  return (
    <>
      {/* メタタグ・タイトル・ファビコン */}
      <Head>
        <title>Cafe Riviera | renewal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Ysabeau&Shippori+Mincho+B1&family=Vollkorn:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet" />
      </Head>

      <Header />
      <Component {...pageProps} />
    </>
  )
}
